# Generated by Django 5.1.15 on 2026-06-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_court_courtmedia_courtsport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='redirect_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
