# Generated by Django 5.1.15 on 2026-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_banner_redirect_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='court',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='court',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
