# Generated by Django 5.1.15 on 2026-07-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_bookingpayment_bookingqrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('NO_SHOW', 'No Show')], default='PENDING_PAYMENT', max_length=30),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['court', 'booking_date', 'booking_status'], name='bookings_court_i_d15be9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_status', 'expires_at'], name='bookings_booking_979745_idx'),
        ),
    ]
