# Generated by Django 5.1.15 on 2026-08-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
