# Generated by Django 5.1.15 on 2026-08-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_tournament_tournamentparticipant_tournamentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentresult',
            name='participant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='db.tournamentparticipant'),
        ),
    ]
