# Generated by Django 5.1.15 on 2026-08-12 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_tournamentresult_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_gateway', models.CharField(default='PHONEPE', max_length=50)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='db.tournamentparticipant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
