# Generated by Django 5.1.15 on 2026-08-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_tournamentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpayment',
            name='type',
            field=models.CharField(default='BOOKING', max_length=50),
        ),
    ]
