# Generated by Django 5.1.15 on 2026-08-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_bookingpayment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpayment',
            name='tournament_participant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='db.tournamentparticipant'),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='db.booking'),
        ),
        migrations.DeleteModel(
            name='TournamentPayment',
        ),
    ]
