# Generated by Django 5.1.15 on 2026-08-13 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_bookingpayment_tournament_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpayment',
            name='tournament_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='db.tournamentparticipant'),
        ),
    ]
