# Generated by Django 5.1.15 on 2026-09-24 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_booking_discount_amount_booking_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Created By')),
                ('updated_by', models.CharField(max_length=255, null=True, verbose_name='Updated By')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usage', to='db.booking')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='db.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promo_code_usages',
                'constraints': [models.UniqueConstraint(fields=('promo_code', 'booking'), name='unique_promo_booking')],
            },
        ),
    ]
