services:
  postgres:
    image: postgres:17
    container_name: genzplayzone-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: H7mP92xQvL8KcT41
      POSTGRES_DB: genzplayzone
      PGSSLMODE: disable

    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

    networks:
      - genzplayzone-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d genzplayzone"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: genzplayzone-backend:latest

    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
      tags:
        - genzplayzone-backend:latest

    container_name: genzplayzone-backend
    restart: unless-stopped

    env_file:
      - ../../.env

    environment:
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_NAME: genzplayzone
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_PASSWORD: H7mP92xQvL8KcT41
      POSTGRES_DB_SSL_ENABLED: "False"

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8013:8000"

    networks:
      - genzplayzone-network

    healthcheck:
      test: ["CMD", "python", "-c", "print('healthy')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:

networks:
  genzplayzone-network:
    external: true